### ISSUE TITLE
Documentation formatting is awful

### ISSUE THREAD

**Issue by adamalton** [googleapis/python-kms#30]
Just cast your eyes over this and then start crying because the formatting is so bad that it's almost unreadable: https://googleapis.dev/python/cloudkms/latest/kms_v1/services.html

My eyes hurt!!

![Screen Shot 2020-07-31 at 15 41 21](https://user-images.githubusercontent.com/270255/89046097-6f7e3380-d344-11ea-9012-ff54f6d4a4cf.png)

**Comment by vchudnov-g** [comment]
The doc pages look different and better now. Compare the initial screenshot with the current content at https://cloud.google.com/python/docs/reference/cloudkms/latest/google.cloud.kms_v1.services.key_management_service.KeyManagementServiceClient#google_cloud_kms_v1_services_key_management_service_KeyManagementServiceClient_asymmetric_decrypt
