### ISSUE TITLE
Breaking change in KeyManagementServiceClient.decrypt

### ISSUE THREAD

**Issue by jpassing** [googleapis/python-kms#34]
#### Environment details

  - OS type and version: Cloud Shell
  - Python version:  Python 3.7.3 
  - pip version: `pip --version`
  - `google-cloud-kms` version: 2.0.0

#### Steps to reproduce

https://googleapis.dev/python/cloudkms/latest/gapic/v1/api.html contains this example:

```
from google.cloud import kms_v1

client = kms_v1.KeyManagementServiceClient()

name = client.crypto_key_path('[PROJECT]', '[LOCATION]', '[KEY_RING]', '[CRYPTO_KEY]')

# TODO: Initialize `ciphertext`:
ciphertext = b''

response = client.decrypt(name, ciphertext)
``` 

**Expected**:  Example works

**Actual**: With 1.0.0, the example worked. With 2.0.0, the example fails:

```
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import kms_v1
>>> client = kms_v1.KeyManagementServiceClient()
>>> name = client.crypto_key_path('[PROJECT]', '[LOCATION]', '[KEY_RING]', '[CRYPTO_KEY]')
>>> ciphertext = b''
>>> response = client.decrypt(name, ciphertext)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: decrypt() takes from 1 to 2 positional arguments but 3 were given
``` 

In one of the last versions, the signature was changed to require the use of named arguments, which constitutes a breaking change. I think the example is right, the implementation is wrong.

**Comment by busunkim96** [comment]
@jpassing I think there is some weirdness in the docs that is a result of us moving things around. If you start at https://googleapis.dev/python/cloudkms/latest/index.html the links go to the correct place. 

https://googleapis.dev/python/cloudkms/latest/UPGRADING.html touches on the main differences in the 2.0 release. It may also be helpful to look at the [samples](https://github.com/googleapis/python-kms/tree/master/samples/snippets).

**Comment by jpassing** [comment]
Ok, I see it's documented. 

I do not think breaking compatibility in such a subtle way is a smart move. There's a good chance you'll break many projects that have not been careful about locking their dependency to 1.xx.
