### ISSUE TITLE
Release Notes: Add crypto_key_path_path to crypto_key_path 

### ISSUE THREAD

**Issue by dylancaponi** [googleapis/python-kms#43]
The snippets were modified to show `crypto_key_path_path` changed to `crypto_key_path` here: https://github.com/googleapis/python-kms/commit/8068e87ff44c768561a1bcfb45ccaadf8dd393ba

It was mentioned in an older synth.py but that TODO was removed: https://github.com/googleapis/python-kms/blob/fa794ffabbcbaaafc3e389228bb13664ac6b7662/synth.py#L49

However, there is no mention or the `crypto_key_path_path` change in [2.0.0 Migration Guide](https://googleapis.dev/python/cloudkms/latest/UPGRADING.html).

**Please consider adding it.**

Thanks!

**Comment by symbiont-ji** [comment]
The documentation: https://googleapis.dev/python/cloudkms/latest/_modules/google/cloud/kms_v1/gapic/key_management_service_client.html#KeyManagementServiceClient.crypto_key_path_path still mentions crypto_key_path_path. Is it *that* hard to keep docs and library in sync?

**Comment by busunkim96** [comment]
Hi @symbiont-ji,

We have an issue where old pages stick around in the `/latest/` alias. However, there is no link or search query that would lead you to that page if you start from https://googleapis.dev/python/cloudkms/latest/kms_v1

https://googleapis.dev/python/cloudkms/latest/search.html?q=crypto_key_path
