### ISSUE TITLE
Import request support or examples

### ISSUE THREAD

**Issue by mlmarius** [googleapis/python-kms#58]
I am trying to programmatically import an asymmetric decrypt key into KMS. I see the API endpoint documentation and have prepared my wrappwed keys but I see no method on the client to submit my key to the import. Examples or suggestions on how to do this using the client instance also seem to be lacking.

Please outline how to submit my key material to the import endpoint using the client or how to extract authentication token from the client and submit using simple https requests.

**Comment by busunkim96** [comment]
Hi @mlmarius,

Do any of these samples show what you're trying to do? https://github.com/googleapis/python-kms/tree/master/samples/snippets

Referencing https://cloud.google.com/kms/docs/quickstart may also be helpful.

**Comment by mlmarius** [comment]
Hi and thanks for the reply @busunkim96 
I've browsed the examples and the documentation but unfortunately was not able to find something that suits my particular case. I actually find it a bit odd that this use case (submitting custom key material to be imported into KMS) is entirely overlooked. I could also try to manage if I had some sort of an escape hatch with which to use the client to dispatch a request to some endpoint of my choosing and include my own payload. If I had such an example I could follow the API docs and get submit my key.

**Comment by busunkim96** [comment]
I don't think KMS has such functionality, but I am not an expert here. If you're looking for a place to store secrets [secret manager](https://cloud.google.com/secret-manager) may be more appropriate.

Paging @sethvargo and @bdhess. Could you take a look?

**Comment by mlmarius** [comment]
Sorry, maybe I've not explained it well.

I am trying to achieve this [importing a key](https://cloud.google.com/kms/docs/importing-a-key) programmatically.
The relevant API endpoint is [this](https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys.cryptoKeyVersions/import)

It's just that I'm using the Python client for my script. It does 90% of what I need it to do and I just need to figure out this last bit.

**Comment by sethvargo** [comment]
We do not currently support importing a key via the client libraries. It's available via the API, gcloud, and the Cloud Console.

**Comment by mlmarius** [comment]
Is there some way to retrieve the authorization token from the client so that I can make my own request? That would be sufficient.

**Comment by sethvargo** [comment]
@busunkim96 - that's a good question for you ^. Is there an easy way to get a "raw" client or execute a raw request using the auth on the cPython lient?

**Comment by bdhess** [comment]
We don't have any samples published, but I threw together a gist of how this can be done from python:
https://gist.github.com/bdhess/3c3a547c6c5289bfd6929e30d866c0bb

There's no need to get a raw/underlying RPC connection.

**Comment by busunkim96** [comment]
If you're interacting with the REST API directly you can use the auth library to get credentials and an `AuthorizedSession` that stores those credentials. 

```py
from google.auth.transport.requests import AuthorizedSession

credentials, _ = google.auth.default()
authed_session = AuthorizedSession(credentials)

response = authed_session.request(
    'GET', 'https://www.googleapis.com/..')
```

**Comment by busunkim96** [comment]
Closing since the original question seems to have been addressed.
